### ISSUE TITLE
Pq tu fez isso em VB ??

### ISSUE THREAD

**Issue by GabrielAyala** [ricardoBpinheiro/BestSoma#1]
Amigão ?? Guttyzada ?? o VB está MORTO !! Não use mais ele, apenas e somente isso, vlw flws

**Comment by ricardoBpinheiro** [comment]
Olá Gabriel Ayala, agradeço por sua issue, mas vou listar aqui alguns motivos para se utilizar o VB.NET ainda nos dias atuais 

O VB.Net não é apenas uma nova versão do Visual Basic que traz algumas melhorias em relação a versão anterior.

Existem alguns artigos em português que você pode consultar para uma visão geral sobre a plataforma .NET :
http://www.microsoft.com/brasil/msdn/tecnologias/visualbasic_bday.asp
http://www.microsoft.com/brasil/msdn/tecnologias/visualbasic_virada1.asp
http://www.microsoft.com/brasil/msdn/tecnologias/visualbasic_webform.asp

 Não sei se você sabe , mas o Visual Basic é acusado com frequência de ser uma linguagem livremente estruturada ; dependendo do programador o código pode degenerar para um estilo de programação direcionado a eventos que espalha fragmentos de código para todos os lados causando muitos problemas.
Pela sua facilidade de aprendizado e utilização o VB atraiu um grande número de pessoas que nunca pensariam em criar programas para a plataforma Windows usando linguagens como C ou C++ ; se por um lado isto popularizou a linguagem , por outro , fez com que uma grande parte do código produzido fosse de baixa qualidade e isto atraiu uma má fama á linguagem.
Nestes últimos tempos a programação orientada a objetos(OOP - Object Oriented Programming Language) tem chamado muito a atenção e ganhado muito espaço entre os desenvolvedores. A utilização das técnicas de orientação a objeto no desenvolvimento de aplicativos facilita a depuração , o aperfeiçoamento , a escalabilidade e a reutilização do código. 
Novamente o VB se viu envolvido em uma celeuma : Ser ou não ser uma linguagem orientada a objetos ? (leia o artigo : Criando Classes no VB )
Rigorosamente falando, até a versão 6.0 , o VB não podia ser considerada uma linguagem que reunisse as características típicas de uma verdadeira linguagem orientada a objetos , como Java por exemplo.
O VB 6.0 não dava suporte a herança ( embora suportasse a implementação de interfaces ).
Com a chegada do VB.NET , você pode dizer de boca cheia : O Visual Basic é uma linguagem orientada a Objetos.
Isto trouxe novas perspectivas e também novas frustrações , a principal delas é a mudança de mentalidade ao se programar em VB.NET com a orientação a objetos.
Geralmente a grande maioria que usa a linguagem Visual Basic conhece a programação tradicional estruturada ; neste modelo o problema geralmente é dividido em duas partes :  os dados e os processos.  Você tem um problema e imediatamente pensa em criar funções que processem determinada tarefa para resolver o problema ou uma parte dele.
Ao final , após muito trabalho, você acaba com uma coleção de funções que juntas compõem a solução do seu problema.
A utilização das técnicas das orientação traz um resultado muito melhor como veremos.

Por isso eu utilizei VB.NET para desenvolver este projeto.
